/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedExecucaoObrasRouteImport } from './routes/_authenticated/execucao-obras'
import { Route as AuthenticatedHistoricoObrasRouteImport } from './routes/_authenticated/historico-obras'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedReunioesRouteImport } from './routes/_authenticated/reunioes'
import { Route as AuthenticatedTramitacoesRouteImport } from './routes/_authenticated/tramitacoes'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes/$id'
import { Route as AuthenticatedExecucaoObrasIndexRouteImport } from './routes/_authenticated/execucao-obras/index'
import { Route as AuthenticatedExecucaoObrasIdRouteImport } from './routes/_authenticated/execucao-obras/$id'
import { Route as AuthenticatedExecucaoObrasNovaRouteImport } from './routes/_authenticated/execucao-obras/nova'
import { Route as AuthenticatedObrasIndexRouteImport } from './routes/_authenticated/obras/index'
import { Route as AuthenticatedObrasIdRouteImport } from './routes/_authenticated/obras/$id'
import { Route as AuthenticatedObrasNovaRouteImport } from './routes/_authenticated/obras/nova'
import { Route as AuthenticatedExecucaoObrasIdIndexRouteImport } from './routes/_authenticated/execucao-obras/$id/index'
import { Route as AuthenticatedExecucaoObrasIdAnalisesCriticasRouteImport } from './routes/_authenticated/execucao-obras/$id/analises-criticas'
import { Route as AuthenticatedExecucaoObrasIdDocumentosEngComercialRouteImport } from './routes/_authenticated/execucao-obras/$id/documentos-eng-comercial'
import { Route as AuthenticatedExecucaoObrasIdEtapasRouteImport } from './routes/_authenticated/execucao-obras/$id/etapas'
import { Route as AuthenticatedExecucaoObrasIdReunioesRouteImport } from './routes/_authenticated/execucao-obras/$id/reunioes'
import { Route as AuthenticatedObrasIdIndexRouteImport } from './routes/_authenticated/obras/$id/index'
import { Route as AuthenticatedObrasIdComercialRouteImport } from './routes/_authenticated/obras/$id/comercial'
import { Route as AuthenticatedObrasIdEditarRouteImport } from './routes/_authenticated/obras/$id/editar'
import { Route as AuthenticatedObrasIdEtapasRouteImport } from './routes/_authenticated/obras/$id/etapas'
import { Route as AuthenticatedObrasIdHistoricoRouteImport } from './routes/_authenticated/obras/$id/historico'
import { Route as AuthenticatedObrasIdOrcamentoRouteImport } from './routes/_authenticated/obras/$id/orcamento'
import { Route as AuthenticatedExecucaoObrasIdDemandasIndexRouteImport } from './routes/_authenticated/execucao-obras/$id/demandas/index'
import { Route as AuthenticatedExecucaoObrasIdDemandasNovaRouteImport } from './routes/_authenticated/execucao-obras/$id/demandas/nova'
import { Route as AuthenticatedObrasIdCronogramaIndexRouteImport } from './routes/_authenticated/obras/$id/cronograma/index'
import { Route as AuthenticatedObrasIdDemandasIndexRouteImport } from './routes/_authenticated/obras/$id/demandas/index'
import { Route as AuthenticatedObrasIdDemandasEditarRouteImport } from './routes/_authenticated/obras/$id/demandas/editar'
import { Route as AuthenticatedObrasIdDemandasNovaRouteImport } from './routes/_authenticated/obras/$id/demandas/nova'
import { Route as AuthenticatedObrasIdDocumentosIndexRouteImport } from './routes/_authenticated/obras/$id/documentos/index'
import { Route as AuthenticatedObrasIdEquipamentosIndexRouteImport } from './routes/_authenticated/obras/$id/equipamentos/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExecucaoObrasRoute =
  AuthenticatedExecucaoObrasRouteImport.update({
    id: '/_authenticated/execucao-obras',
    path: '/execucao-obras',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHistoricoObrasRoute =
  AuthenticatedHistoricoObrasRouteImport.update({
    id: '/_authenticated/historico-obras',
    path: '/historico-obras',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/_authenticated/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReunioesRoute = AuthenticatedReunioesRouteImport.update({
  id: '/_authenticated/reunioes',
  path: '/reunioes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTramitacoesRoute =
  AuthenticatedTramitacoesRouteImport.update({
    id: '/_authenticated/tramitacoes',
    path: '/tramitacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/_authenticated/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExecucaoObrasIndexRoute =
  AuthenticatedExecucaoObrasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExecucaoObrasRoute,
  } as any)
const AuthenticatedExecucaoObrasIdRoute =
  AuthenticatedExecucaoObrasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedExecucaoObrasRoute,
  } as any)
const AuthenticatedExecucaoObrasNovaRoute =
  AuthenticatedExecucaoObrasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedExecucaoObrasRoute,
  } as any)
const AuthenticatedObrasIndexRoute = AuthenticatedObrasIndexRouteImport.update({
  id: '/_authenticated/obras/',
  path: '/obras/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedObrasIdRoute = AuthenticatedObrasIdRouteImport.update({
  id: '/_authenticated/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedObrasNovaRoute = AuthenticatedObrasNovaRouteImport.update({
  id: '/_authenticated/obras/nova',
  path: '/obras/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExecucaoObrasIdIndexRoute =
  AuthenticatedExecucaoObrasIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExecucaoObrasIdRoute,
  } as any)
const AuthenticatedExecucaoObrasIdAnalisesCriticasRoute =
  AuthenticatedExecucaoObrasIdAnalisesCriticasRouteImport.update({
    id: '/analises-criticas',
    path: '/analises-criticas',
    getParentRoute: () => AuthenticatedExecucaoObrasIdRoute,
  } as any)
const AuthenticatedExecucaoObrasIdDocumentosEngComercialRoute =
  AuthenticatedExecucaoObrasIdDocumentosEngComercialRouteImport.update({
    id: '/documentos-eng-comercial',
    path: '/documentos-eng-comercial',
    getParentRoute: () => AuthenticatedExecucaoObrasIdRoute,
  } as any)
const AuthenticatedExecucaoObrasIdEtapasRoute =
  AuthenticatedExecucaoObrasIdEtapasRouteImport.update({
    id: '/etapas',
    path: '/etapas',
    getParentRoute: () => AuthenticatedExecucaoObrasIdRoute,
  } as any)
const AuthenticatedExecucaoObrasIdReunioesRoute =
  AuthenticatedExecucaoObrasIdReunioesRouteImport.update({
    id: '/reunioes',
    path: '/reunioes',
    getParentRoute: () => AuthenticatedExecucaoObrasIdRoute,
  } as any)
const AuthenticatedObrasIdIndexRoute =
  AuthenticatedObrasIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedObrasIdComercialRoute =
  AuthenticatedObrasIdComercialRouteImport.update({
    id: '/comercial',
    path: '/comercial',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedObrasIdEditarRoute =
  AuthenticatedObrasIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedObrasIdEtapasRoute =
  AuthenticatedObrasIdEtapasRouteImport.update({
    id: '/etapas',
    path: '/etapas',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedObrasIdHistoricoRoute =
  AuthenticatedObrasIdHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedObrasIdOrcamentoRoute =
  AuthenticatedObrasIdOrcamentoRouteImport.update({
    id: '/orcamento',
    path: '/orcamento',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedExecucaoObrasIdDemandasIndexRoute =
  AuthenticatedExecucaoObrasIdDemandasIndexRouteImport.update({
    id: '/demandas/',
    path: '/demandas/',
    getParentRoute: () => AuthenticatedExecucaoObrasIdRoute,
  } as any)
const AuthenticatedExecucaoObrasIdDemandasNovaRoute =
  AuthenticatedExecucaoObrasIdDemandasNovaRouteImport.update({
    id: '/demandas/nova',
    path: '/demandas/nova',
    getParentRoute: () => AuthenticatedExecucaoObrasIdRoute,
  } as any)
const AuthenticatedObrasIdCronogramaIndexRoute =
  AuthenticatedObrasIdCronogramaIndexRouteImport.update({
    id: '/cronograma/',
    path: '/cronograma/',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedObrasIdDemandasIndexRoute =
  AuthenticatedObrasIdDemandasIndexRouteImport.update({
    id: '/demandas/',
    path: '/demandas/',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedObrasIdDemandasEditarRoute =
  AuthenticatedObrasIdDemandasEditarRouteImport.update({
    id: '/demandas/editar',
    path: '/demandas/editar',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedObrasIdDemandasNovaRoute =
  AuthenticatedObrasIdDemandasNovaRouteImport.update({
    id: '/demandas/nova',
    path: '/demandas/nova',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedObrasIdDocumentosIndexRoute =
  AuthenticatedObrasIdDocumentosIndexRouteImport.update({
    id: '/documentos/',
    path: '/documentos/',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)
const AuthenticatedObrasIdEquipamentosIndexRoute =
  AuthenticatedObrasIdEquipamentosIndexRouteImport.update({
    id: '/equipamentos/',
    path: '/equipamentos/',
    getParentRoute: () => AuthenticatedObrasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/execucao-obras': typeof AuthenticatedExecucaoObrasRouteWithChildren
  '/historico-obras': typeof AuthenticatedHistoricoObrasRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
  '/tramitacoes': typeof AuthenticatedTramitacoesRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/execucao-obras/$id': typeof AuthenticatedExecucaoObrasIdRouteWithChildren
  '/execucao-obras/nova': typeof AuthenticatedExecucaoObrasNovaRoute
  '/obras/$id': typeof AuthenticatedObrasIdRouteWithChildren
  '/obras/nova': typeof AuthenticatedObrasNovaRoute
  '/execucao-obras/': typeof AuthenticatedExecucaoObrasIndexRoute
  '/obras/': typeof AuthenticatedObrasIndexRoute
  '/execucao-obras/$id/analises-criticas': typeof AuthenticatedExecucaoObrasIdAnalisesCriticasRoute
  '/execucao-obras/$id/documentos-eng-comercial': typeof AuthenticatedExecucaoObrasIdDocumentosEngComercialRoute
  '/execucao-obras/$id/etapas': typeof AuthenticatedExecucaoObrasIdEtapasRoute
  '/execucao-obras/$id/reunioes': typeof AuthenticatedExecucaoObrasIdReunioesRoute
  '/obras/$id/comercial': typeof AuthenticatedObrasIdComercialRoute
  '/obras/$id/editar': typeof AuthenticatedObrasIdEditarRoute
  '/obras/$id/etapas': typeof AuthenticatedObrasIdEtapasRoute
  '/obras/$id/historico': typeof AuthenticatedObrasIdHistoricoRoute
  '/obras/$id/orcamento': typeof AuthenticatedObrasIdOrcamentoRoute
  '/execucao-obras/$id/': typeof AuthenticatedExecucaoObrasIdIndexRoute
  '/obras/$id/': typeof AuthenticatedObrasIdIndexRoute
  '/execucao-obras/$id/demandas/nova': typeof AuthenticatedExecucaoObrasIdDemandasNovaRoute
  '/obras/$id/demandas/editar': typeof AuthenticatedObrasIdDemandasEditarRoute
  '/obras/$id/demandas/nova': typeof AuthenticatedObrasIdDemandasNovaRoute
  '/execucao-obras/$id/demandas/': typeof AuthenticatedExecucaoObrasIdDemandasIndexRoute
  '/obras/$id/cronograma/': typeof AuthenticatedObrasIdCronogramaIndexRoute
  '/obras/$id/demandas/': typeof AuthenticatedObrasIdDemandasIndexRoute
  '/obras/$id/documentos/': typeof AuthenticatedObrasIdDocumentosIndexRoute
  '/obras/$id/equipamentos/': typeof AuthenticatedObrasIdEquipamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/historico-obras': typeof AuthenticatedHistoricoObrasRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
  '/tramitacoes': typeof AuthenticatedTramitacoesRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/execucao-obras/nova': typeof AuthenticatedExecucaoObrasNovaRoute
  '/obras/nova': typeof AuthenticatedObrasNovaRoute
  '/execucao-obras': typeof AuthenticatedExecucaoObrasIndexRoute
  '/obras': typeof AuthenticatedObrasIndexRoute
  '/execucao-obras/$id/analises-criticas': typeof AuthenticatedExecucaoObrasIdAnalisesCriticasRoute
  '/execucao-obras/$id/documentos-eng-comercial': typeof AuthenticatedExecucaoObrasIdDocumentosEngComercialRoute
  '/execucao-obras/$id/etapas': typeof AuthenticatedExecucaoObrasIdEtapasRoute
  '/execucao-obras/$id/reunioes': typeof AuthenticatedExecucaoObrasIdReunioesRoute
  '/obras/$id/comercial': typeof AuthenticatedObrasIdComercialRoute
  '/obras/$id/editar': typeof AuthenticatedObrasIdEditarRoute
  '/obras/$id/etapas': typeof AuthenticatedObrasIdEtapasRoute
  '/obras/$id/historico': typeof AuthenticatedObrasIdHistoricoRoute
  '/obras/$id/orcamento': typeof AuthenticatedObrasIdOrcamentoRoute
  '/execucao-obras/$id': typeof AuthenticatedExecucaoObrasIdIndexRoute
  '/obras/$id': typeof AuthenticatedObrasIdIndexRoute
  '/execucao-obras/$id/demandas/nova': typeof AuthenticatedExecucaoObrasIdDemandasNovaRoute
  '/obras/$id/demandas/editar': typeof AuthenticatedObrasIdDemandasEditarRoute
  '/obras/$id/demandas/nova': typeof AuthenticatedObrasIdDemandasNovaRoute
  '/execucao-obras/$id/demandas': typeof AuthenticatedExecucaoObrasIdDemandasIndexRoute
  '/obras/$id/cronograma': typeof AuthenticatedObrasIdCronogramaIndexRoute
  '/obras/$id/demandas': typeof AuthenticatedObrasIdDemandasIndexRoute
  '/obras/$id/documentos': typeof AuthenticatedObrasIdDocumentosIndexRoute
  '/obras/$id/equipamentos': typeof AuthenticatedObrasIdEquipamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/execucao-obras': typeof AuthenticatedExecucaoObrasRouteWithChildren
  '/_authenticated/historico-obras': typeof AuthenticatedHistoricoObrasRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/reunioes': typeof AuthenticatedReunioesRoute
  '/_authenticated/tramitacoes': typeof AuthenticatedTramitacoesRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/execucao-obras/$id': typeof AuthenticatedExecucaoObrasIdRouteWithChildren
  '/_authenticated/execucao-obras/nova': typeof AuthenticatedExecucaoObrasNovaRoute
  '/_authenticated/obras/$id': typeof AuthenticatedObrasIdRouteWithChildren
  '/_authenticated/obras/nova': typeof AuthenticatedObrasNovaRoute
  '/_authenticated/execucao-obras/': typeof AuthenticatedExecucaoObrasIndexRoute
  '/_authenticated/obras/': typeof AuthenticatedObrasIndexRoute
  '/_authenticated/execucao-obras/$id/analises-criticas': typeof AuthenticatedExecucaoObrasIdAnalisesCriticasRoute
  '/_authenticated/execucao-obras/$id/documentos-eng-comercial': typeof AuthenticatedExecucaoObrasIdDocumentosEngComercialRoute
  '/_authenticated/execucao-obras/$id/etapas': typeof AuthenticatedExecucaoObrasIdEtapasRoute
  '/_authenticated/execucao-obras/$id/reunioes': typeof AuthenticatedExecucaoObrasIdReunioesRoute
  '/_authenticated/obras/$id/comercial': typeof AuthenticatedObrasIdComercialRoute
  '/_authenticated/obras/$id/editar': typeof AuthenticatedObrasIdEditarRoute
  '/_authenticated/obras/$id/etapas': typeof AuthenticatedObrasIdEtapasRoute
  '/_authenticated/obras/$id/historico': typeof AuthenticatedObrasIdHistoricoRoute
  '/_authenticated/obras/$id/orcamento': typeof AuthenticatedObrasIdOrcamentoRoute
  '/_authenticated/execucao-obras/$id/': typeof AuthenticatedExecucaoObrasIdIndexRoute
  '/_authenticated/obras/$id/': typeof AuthenticatedObrasIdIndexRoute
  '/_authenticated/execucao-obras/$id/demandas/nova': typeof AuthenticatedExecucaoObrasIdDemandasNovaRoute
  '/_authenticated/obras/$id/demandas/editar': typeof AuthenticatedObrasIdDemandasEditarRoute
  '/_authenticated/obras/$id/demandas/nova': typeof AuthenticatedObrasIdDemandasNovaRoute
  '/_authenticated/execucao-obras/$id/demandas/': typeof AuthenticatedExecucaoObrasIdDemandasIndexRoute
  '/_authenticated/obras/$id/cronograma/': typeof AuthenticatedObrasIdCronogramaIndexRoute
  '/_authenticated/obras/$id/demandas/': typeof AuthenticatedObrasIdDemandasIndexRoute
  '/_authenticated/obras/$id/documentos/': typeof AuthenticatedObrasIdDocumentosIndexRoute
  '/_authenticated/obras/$id/equipamentos/': typeof AuthenticatedObrasIdEquipamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/clientes'
    | '/login'
    | '/relatorios'
    | '/admin'
    | '/execucao-obras'
    | '/historico-obras'
    | '/minha-conta'
    | '/reunioes'
    | '/tramitacoes'
    | '/clientes/$id'
    | '/execucao-obras/$id'
    | '/execucao-obras/nova'
    | '/obras/$id'
    | '/obras/nova'
    | '/execucao-obras/'
    | '/obras/'
    | '/execucao-obras/$id/analises-criticas'
    | '/execucao-obras/$id/documentos-eng-comercial'
    | '/execucao-obras/$id/etapas'
    | '/execucao-obras/$id/reunioes'
    | '/obras/$id/comercial'
    | '/obras/$id/editar'
    | '/obras/$id/etapas'
    | '/obras/$id/historico'
    | '/obras/$id/orcamento'
    | '/execucao-obras/$id/'
    | '/obras/$id/'
    | '/execucao-obras/$id/demandas/nova'
    | '/obras/$id/demandas/editar'
    | '/obras/$id/demandas/nova'
    | '/execucao-obras/$id/demandas/'
    | '/obras/$id/cronograma/'
    | '/obras/$id/demandas/'
    | '/obras/$id/documentos/'
    | '/obras/$id/equipamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/clientes'
    | '/login'
    | '/relatorios'
    | '/admin'
    | '/historico-obras'
    | '/minha-conta'
    | '/reunioes'
    | '/tramitacoes'
    | '/clientes/$id'
    | '/execucao-obras/nova'
    | '/obras/nova'
    | '/execucao-obras'
    | '/obras'
    | '/execucao-obras/$id/analises-criticas'
    | '/execucao-obras/$id/documentos-eng-comercial'
    | '/execucao-obras/$id/etapas'
    | '/execucao-obras/$id/reunioes'
    | '/obras/$id/comercial'
    | '/obras/$id/editar'
    | '/obras/$id/etapas'
    | '/obras/$id/historico'
    | '/obras/$id/orcamento'
    | '/execucao-obras/$id'
    | '/obras/$id'
    | '/execucao-obras/$id/demandas/nova'
    | '/obras/$id/demandas/editar'
    | '/obras/$id/demandas/nova'
    | '/execucao-obras/$id/demandas'
    | '/obras/$id/cronograma'
    | '/obras/$id/demandas'
    | '/obras/$id/documentos'
    | '/obras/$id/equipamentos'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/clientes'
    | '/login'
    | '/relatorios'
    | '/_authenticated/admin'
    | '/_authenticated/execucao-obras'
    | '/_authenticated/historico-obras'
    | '/_authenticated/minha-conta'
    | '/_authenticated/reunioes'
    | '/_authenticated/tramitacoes'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/execucao-obras/$id'
    | '/_authenticated/execucao-obras/nova'
    | '/_authenticated/obras/$id'
    | '/_authenticated/obras/nova'
    | '/_authenticated/execucao-obras/'
    | '/_authenticated/obras/'
    | '/_authenticated/execucao-obras/$id/analises-criticas'
    | '/_authenticated/execucao-obras/$id/documentos-eng-comercial'
    | '/_authenticated/execucao-obras/$id/etapas'
    | '/_authenticated/execucao-obras/$id/reunioes'
    | '/_authenticated/obras/$id/comercial'
    | '/_authenticated/obras/$id/editar'
    | '/_authenticated/obras/$id/etapas'
    | '/_authenticated/obras/$id/historico'
    | '/_authenticated/obras/$id/orcamento'
    | '/_authenticated/execucao-obras/$id/'
    | '/_authenticated/obras/$id/'
    | '/_authenticated/execucao-obras/$id/demandas/nova'
    | '/_authenticated/obras/$id/demandas/editar'
    | '/_authenticated/obras/$id/demandas/nova'
    | '/_authenticated/execucao-obras/$id/demandas/'
    | '/_authenticated/obras/$id/cronograma/'
    | '/_authenticated/obras/$id/demandas/'
    | '/_authenticated/obras/$id/documentos/'
    | '/_authenticated/obras/$id/equipamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ClientesRoute: typeof ClientesRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedExecucaoObrasRoute: typeof AuthenticatedExecucaoObrasRouteWithChildren
  AuthenticatedHistoricoObrasRoute: typeof AuthenticatedHistoricoObrasRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedReunioesRoute: typeof AuthenticatedReunioesRoute
  AuthenticatedTramitacoesRoute: typeof AuthenticatedTramitacoesRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedObrasIdRoute: typeof AuthenticatedObrasIdRouteWithChildren
  AuthenticatedObrasNovaRoute: typeof AuthenticatedObrasNovaRoute
  AuthenticatedObrasIndexRoute: typeof AuthenticatedObrasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/execucao-obras': {
      id: '/_authenticated/execucao-obras'
      path: '/execucao-obras'
      fullPath: '/execucao-obras'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico-obras': {
      id: '/_authenticated/historico-obras'
      path: '/historico-obras'
      fullPath: '/historico-obras'
      preLoaderRoute: typeof AuthenticatedHistoricoObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reunioes': {
      id: '/_authenticated/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AuthenticatedReunioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tramitacoes': {
      id: '/_authenticated/tramitacoes'
      path: '/tramitacoes'
      fullPath: '/tramitacoes'
      preLoaderRoute: typeof AuthenticatedTramitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/execucao-obras/': {
      id: '/_authenticated/execucao-obras/'
      path: '/'
      fullPath: '/execucao-obras/'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasIndexRouteImport
      parentRoute: typeof AuthenticatedExecucaoObrasRoute
    }
    '/_authenticated/execucao-obras/$id': {
      id: '/_authenticated/execucao-obras/$id'
      path: '/$id'
      fullPath: '/execucao-obras/$id'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasIdRouteImport
      parentRoute: typeof AuthenticatedExecucaoObrasRoute
    }
    '/_authenticated/execucao-obras/nova': {
      id: '/_authenticated/execucao-obras/nova'
      path: '/nova'
      fullPath: '/execucao-obras/nova'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasNovaRouteImport
      parentRoute: typeof AuthenticatedExecucaoObrasRoute
    }
    '/_authenticated/obras/': {
      id: '/_authenticated/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof AuthenticatedObrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/obras/$id': {
      id: '/_authenticated/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof AuthenticatedObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/obras/nova': {
      id: '/_authenticated/obras/nova'
      path: '/obras/nova'
      fullPath: '/obras/nova'
      preLoaderRoute: typeof AuthenticatedObrasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/execucao-obras/$id/': {
      id: '/_authenticated/execucao-obras/$id/'
      path: '/'
      fullPath: '/execucao-obras/$id/'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasIdIndexRouteImport
      parentRoute: typeof AuthenticatedExecucaoObrasIdRoute
    }
    '/_authenticated/execucao-obras/$id/analises-criticas': {
      id: '/_authenticated/execucao-obras/$id/analises-criticas'
      path: '/analises-criticas'
      fullPath: '/execucao-obras/$id/analises-criticas'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasIdAnalisesCriticasRouteImport
      parentRoute: typeof AuthenticatedExecucaoObrasIdRoute
    }
    '/_authenticated/execucao-obras/$id/documentos-eng-comercial': {
      id: '/_authenticated/execucao-obras/$id/documentos-eng-comercial'
      path: '/documentos-eng-comercial'
      fullPath: '/execucao-obras/$id/documentos-eng-comercial'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasIdDocumentosEngComercialRouteImport
      parentRoute: typeof AuthenticatedExecucaoObrasIdRoute
    }
    '/_authenticated/execucao-obras/$id/etapas': {
      id: '/_authenticated/execucao-obras/$id/etapas'
      path: '/etapas'
      fullPath: '/execucao-obras/$id/etapas'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasIdEtapasRouteImport
      parentRoute: typeof AuthenticatedExecucaoObrasIdRoute
    }
    '/_authenticated/execucao-obras/$id/reunioes': {
      id: '/_authenticated/execucao-obras/$id/reunioes'
      path: '/reunioes'
      fullPath: '/execucao-obras/$id/reunioes'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasIdReunioesRouteImport
      parentRoute: typeof AuthenticatedExecucaoObrasIdRoute
    }
    '/_authenticated/obras/$id/': {
      id: '/_authenticated/obras/$id/'
      path: '/'
      fullPath: '/obras/$id/'
      preLoaderRoute: typeof AuthenticatedObrasIdIndexRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/obras/$id/comercial': {
      id: '/_authenticated/obras/$id/comercial'
      path: '/comercial'
      fullPath: '/obras/$id/comercial'
      preLoaderRoute: typeof AuthenticatedObrasIdComercialRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/obras/$id/editar': {
      id: '/_authenticated/obras/$id/editar'
      path: '/editar'
      fullPath: '/obras/$id/editar'
      preLoaderRoute: typeof AuthenticatedObrasIdEditarRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/obras/$id/etapas': {
      id: '/_authenticated/obras/$id/etapas'
      path: '/etapas'
      fullPath: '/obras/$id/etapas'
      preLoaderRoute: typeof AuthenticatedObrasIdEtapasRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/obras/$id/historico': {
      id: '/_authenticated/obras/$id/historico'
      path: '/historico'
      fullPath: '/obras/$id/historico'
      preLoaderRoute: typeof AuthenticatedObrasIdHistoricoRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/obras/$id/orcamento': {
      id: '/_authenticated/obras/$id/orcamento'
      path: '/orcamento'
      fullPath: '/obras/$id/orcamento'
      preLoaderRoute: typeof AuthenticatedObrasIdOrcamentoRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/execucao-obras/$id/demandas/': {
      id: '/_authenticated/execucao-obras/$id/demandas/'
      path: '/demandas'
      fullPath: '/execucao-obras/$id/demandas/'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasIdDemandasIndexRouteImport
      parentRoute: typeof AuthenticatedExecucaoObrasIdRoute
    }
    '/_authenticated/execucao-obras/$id/demandas/nova': {
      id: '/_authenticated/execucao-obras/$id/demandas/nova'
      path: '/demandas/nova'
      fullPath: '/execucao-obras/$id/demandas/nova'
      preLoaderRoute: typeof AuthenticatedExecucaoObrasIdDemandasNovaRouteImport
      parentRoute: typeof AuthenticatedExecucaoObrasIdRoute
    }
    '/_authenticated/obras/$id/cronograma/': {
      id: '/_authenticated/obras/$id/cronograma/'
      path: '/cronograma'
      fullPath: '/obras/$id/cronograma/'
      preLoaderRoute: typeof AuthenticatedObrasIdCronogramaIndexRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/obras/$id/demandas/': {
      id: '/_authenticated/obras/$id/demandas/'
      path: '/demandas'
      fullPath: '/obras/$id/demandas/'
      preLoaderRoute: typeof AuthenticatedObrasIdDemandasIndexRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/obras/$id/demandas/editar': {
      id: '/_authenticated/obras/$id/demandas/editar'
      path: '/demandas/editar'
      fullPath: '/obras/$id/demandas/editar'
      preLoaderRoute: typeof AuthenticatedObrasIdDemandasEditarRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/obras/$id/demandas/nova': {
      id: '/_authenticated/obras/$id/demandas/nova'
      path: '/demandas/nova'
      fullPath: '/obras/$id/demandas/nova'
      preLoaderRoute: typeof AuthenticatedObrasIdDemandasNovaRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/obras/$id/documentos/': {
      id: '/_authenticated/obras/$id/documentos/'
      path: '/documentos'
      fullPath: '/obras/$id/documentos/'
      preLoaderRoute: typeof AuthenticatedObrasIdDocumentosIndexRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
    '/_authenticated/obras/$id/equipamentos/': {
      id: '/_authenticated/obras/$id/equipamentos/'
      path: '/equipamentos'
      fullPath: '/obras/$id/equipamentos/'
      preLoaderRoute: typeof AuthenticatedObrasIdEquipamentosIndexRouteImport
      parentRoute: typeof AuthenticatedObrasIdRoute
    }
  }
}

interface AuthenticatedExecucaoObrasIdRouteChildren {
  AuthenticatedExecucaoObrasIdAnalisesCriticasRoute: typeof AuthenticatedExecucaoObrasIdAnalisesCriticasRoute
  AuthenticatedExecucaoObrasIdDocumentosEngComercialRoute: typeof AuthenticatedExecucaoObrasIdDocumentosEngComercialRoute
  AuthenticatedExecucaoObrasIdEtapasRoute: typeof AuthenticatedExecucaoObrasIdEtapasRoute
  AuthenticatedExecucaoObrasIdReunioesRoute: typeof AuthenticatedExecucaoObrasIdReunioesRoute
  AuthenticatedExecucaoObrasIdIndexRoute: typeof AuthenticatedExecucaoObrasIdIndexRoute
  AuthenticatedExecucaoObrasIdDemandasNovaRoute: typeof AuthenticatedExecucaoObrasIdDemandasNovaRoute
  AuthenticatedExecucaoObrasIdDemandasIndexRoute: typeof AuthenticatedExecucaoObrasIdDemandasIndexRoute
}

const AuthenticatedExecucaoObrasIdRouteChildren: AuthenticatedExecucaoObrasIdRouteChildren =
  {
    AuthenticatedExecucaoObrasIdAnalisesCriticasRoute:
      AuthenticatedExecucaoObrasIdAnalisesCriticasRoute,
    AuthenticatedExecucaoObrasIdDocumentosEngComercialRoute:
      AuthenticatedExecucaoObrasIdDocumentosEngComercialRoute,
    AuthenticatedExecucaoObrasIdEtapasRoute:
      AuthenticatedExecucaoObrasIdEtapasRoute,
    AuthenticatedExecucaoObrasIdReunioesRoute:
      AuthenticatedExecucaoObrasIdReunioesRoute,
    AuthenticatedExecucaoObrasIdIndexRoute:
      AuthenticatedExecucaoObrasIdIndexRoute,
    AuthenticatedExecucaoObrasIdDemandasNovaRoute:
      AuthenticatedExecucaoObrasIdDemandasNovaRoute,
    AuthenticatedExecucaoObrasIdDemandasIndexRoute:
      AuthenticatedExecucaoObrasIdDemandasIndexRoute,
  }

const AuthenticatedExecucaoObrasIdRouteWithChildren =
  AuthenticatedExecucaoObrasIdRoute._addFileChildren(
    AuthenticatedExecucaoObrasIdRouteChildren,
  )

interface AuthenticatedExecucaoObrasRouteChildren {
  AuthenticatedExecucaoObrasIdRoute: typeof AuthenticatedExecucaoObrasIdRouteWithChildren
  AuthenticatedExecucaoObrasNovaRoute: typeof AuthenticatedExecucaoObrasNovaRoute
  AuthenticatedExecucaoObrasIndexRoute: typeof AuthenticatedExecucaoObrasIndexRoute
}

const AuthenticatedExecucaoObrasRouteChildren: AuthenticatedExecucaoObrasRouteChildren =
  {
    AuthenticatedExecucaoObrasIdRoute:
      AuthenticatedExecucaoObrasIdRouteWithChildren,
    AuthenticatedExecucaoObrasNovaRoute: AuthenticatedExecucaoObrasNovaRoute,
    AuthenticatedExecucaoObrasIndexRoute: AuthenticatedExecucaoObrasIndexRoute,
  }

const AuthenticatedExecucaoObrasRouteWithChildren =
  AuthenticatedExecucaoObrasRoute._addFileChildren(
    AuthenticatedExecucaoObrasRouteChildren,
  )

interface AuthenticatedObrasIdRouteChildren {
  AuthenticatedObrasIdComercialRoute: typeof AuthenticatedObrasIdComercialRoute
  AuthenticatedObrasIdEditarRoute: typeof AuthenticatedObrasIdEditarRoute
  AuthenticatedObrasIdEtapasRoute: typeof AuthenticatedObrasIdEtapasRoute
  AuthenticatedObrasIdHistoricoRoute: typeof AuthenticatedObrasIdHistoricoRoute
  AuthenticatedObrasIdOrcamentoRoute: typeof AuthenticatedObrasIdOrcamentoRoute
  AuthenticatedObrasIdIndexRoute: typeof AuthenticatedObrasIdIndexRoute
  AuthenticatedObrasIdDemandasEditarRoute: typeof AuthenticatedObrasIdDemandasEditarRoute
  AuthenticatedObrasIdDemandasNovaRoute: typeof AuthenticatedObrasIdDemandasNovaRoute
  AuthenticatedObrasIdCronogramaIndexRoute: typeof AuthenticatedObrasIdCronogramaIndexRoute
  AuthenticatedObrasIdDemandasIndexRoute: typeof AuthenticatedObrasIdDemandasIndexRoute
  AuthenticatedObrasIdDocumentosIndexRoute: typeof AuthenticatedObrasIdDocumentosIndexRoute
  AuthenticatedObrasIdEquipamentosIndexRoute: typeof AuthenticatedObrasIdEquipamentosIndexRoute
}

const AuthenticatedObrasIdRouteChildren: AuthenticatedObrasIdRouteChildren = {
  AuthenticatedObrasIdComercialRoute: AuthenticatedObrasIdComercialRoute,
  AuthenticatedObrasIdEditarRoute: AuthenticatedObrasIdEditarRoute,
  AuthenticatedObrasIdEtapasRoute: AuthenticatedObrasIdEtapasRoute,
  AuthenticatedObrasIdHistoricoRoute: AuthenticatedObrasIdHistoricoRoute,
  AuthenticatedObrasIdOrcamentoRoute: AuthenticatedObrasIdOrcamentoRoute,
  AuthenticatedObrasIdIndexRoute: AuthenticatedObrasIdIndexRoute,
  AuthenticatedObrasIdDemandasEditarRoute:
    AuthenticatedObrasIdDemandasEditarRoute,
  AuthenticatedObrasIdDemandasNovaRoute: AuthenticatedObrasIdDemandasNovaRoute,
  AuthenticatedObrasIdCronogramaIndexRoute:
    AuthenticatedObrasIdCronogramaIndexRoute,
  AuthenticatedObrasIdDemandasIndexRoute:
    AuthenticatedObrasIdDemandasIndexRoute,
  AuthenticatedObrasIdDocumentosIndexRoute:
    AuthenticatedObrasIdDocumentosIndexRoute,
  AuthenticatedObrasIdEquipamentosIndexRoute:
    AuthenticatedObrasIdEquipamentosIndexRoute,
}

const AuthenticatedObrasIdRouteWithChildren =
  AuthenticatedObrasIdRoute._addFileChildren(AuthenticatedObrasIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ClientesRoute: ClientesRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedExecucaoObrasRoute: AuthenticatedExecucaoObrasRouteWithChildren,
  AuthenticatedHistoricoObrasRoute: AuthenticatedHistoricoObrasRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedReunioesRoute: AuthenticatedReunioesRoute,
  AuthenticatedTramitacoesRoute: AuthenticatedTramitacoesRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedObrasIdRoute: AuthenticatedObrasIdRouteWithChildren,
  AuthenticatedObrasNovaRoute: AuthenticatedObrasNovaRoute,
  AuthenticatedObrasIndexRoute: AuthenticatedObrasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
