/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as AuthenticatedObrasIndexRouteImport } from './routes/_authenticated/obras/index'
import { Route as AuthenticatedObrasIdRouteImport } from './routes/_authenticated/obras/$id'
import { Route as AuthenticatedObrasNovaRouteImport } from './routes/_authenticated/obras/nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedObrasIndexRoute = AuthenticatedObrasIndexRouteImport.update({
  id: '/_authenticated/obras/',
  path: '/obras/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedObrasIdRoute = AuthenticatedObrasIdRouteImport.update({
  id: '/_authenticated/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedObrasNovaRoute = AuthenticatedObrasNovaRouteImport.update({
  id: '/_authenticated/obras/nova',
  path: '/obras/nova',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/relatorios': typeof RelatoriosRoute
  '/obras/$id': typeof AuthenticatedObrasIdRoute
  '/obras/nova': typeof AuthenticatedObrasNovaRoute
  '/obras/': typeof AuthenticatedObrasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/obras': typeof AuthenticatedObrasIndexRoute
  '/relatorios': typeof RelatoriosRoute
  '/obras/$id': typeof AuthenticatedObrasIdRoute
  '/obras/nova': typeof AuthenticatedObrasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/relatorios': typeof RelatoriosRoute
  '/_authenticated/obras/$id': typeof AuthenticatedObrasIdRoute
  '/_authenticated/obras/nova': typeof AuthenticatedObrasNovaRoute
  '/_authenticated/obras/': typeof AuthenticatedObrasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/login'
    | '/obras'
    | '/relatorios'
    | '/obras/$id'
    | '/obras/nova'
    | '/obras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/login'
    | '/obras'
    | '/relatorios'
    | '/obras/$id'
    | '/obras/nova'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/login'
    | '/obras'
    | '/relatorios'
    | '/_authenticated/obras/$id'
    | '/_authenticated/obras/nova'
    | '/_authenticated/obras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  LoginRoute: typeof LoginRoute
  ObrasRoute: typeof ObrasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  AuthenticatedObrasIdRoute: typeof AuthenticatedObrasIdRoute
  AuthenticatedObrasNovaRoute: typeof AuthenticatedObrasNovaRoute
  AuthenticatedObrasIndexRoute: typeof AuthenticatedObrasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/obras/': {
      id: '/_authenticated/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof AuthenticatedObrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/obras/$id': {
      id: '/_authenticated/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof AuthenticatedObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/obras/nova': {
      id: '/_authenticated/obras/nova'
      path: '/obras/nova'
      fullPath: '/obras/nova'
      preLoaderRoute: typeof AuthenticatedObrasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  LoginRoute: LoginRoute,
  ObrasRoute: ObrasRoute,
  RelatoriosRoute: RelatoriosRoute,
  AuthenticatedObrasIdRoute: AuthenticatedObrasIdRoute,
  AuthenticatedObrasNovaRoute: AuthenticatedObrasNovaRoute,
  AuthenticatedObrasIndexRoute: AuthenticatedObrasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
